### ISSUE TITLE
[Integration Request] Add commitlint

### ISSUE THREAD

**Issue by rluvaton** [irevenko/forge-node-app#1]
Could you please add commitlint option

**Comment by irevenko** [comment]
🥳 Hello and thank you for opening the issue!
🤔 Can you describe how you see this feature?
🥴 Should i only install the commitlint or there is some extra work to it?

**Comment by irevenko** [comment]
> Could you please add commitlint option


> Could you please add commitlint option
🥳 Hello and thank you for opening the issue!
🤔 Can you describe how you see this feature?
🥴 Should i only install the commitlint or there is some extra work to it?

**Comment by irevenko** [comment]
> Could you please add commitlint option

🥳 Hello @rluvaton and thank you for opening the issue!
🤔 Can you describe how you see this feature?
🥴 Should i only install the commitlint or there is some extra work to it?

**Comment by rluvaton** [comment]
> > Could you please add commitlint option
> 
> 
> 
> 🥳 Hello @rluvaton and thank you for opening the issue!
> 
> 🤔 Can you describe how you see this feature?

Use it in the same convenient way that I use to set the other parameters

> 🥴 Should i only install the commitlint or there is some extra work to it?

You should install the library and add some basic config file

**Comment by irevenko** [comment]
😃 I might do this until christmas 🎇 🎆

**Comment by irevenko** [comment]
@rluvaton I'm back to business 😎
🤖 Gonna work on this Integration Request

**Comment by irevenko** [comment]
@rluvaton i've been pretty busy with https://github.com/irevenko/what-anime-cli so might be able to do on the next week! 😅

**Comment by irevenko** [comment]
@rluvaton 😑 Not in the mood, do not feel like i would support this project any more. Feel free to create your version which would have pnpm and commitlint, good luck 🤞

**Comment by rluvaton** [comment]
> @rluvaton 😑 Not in the mood, do not feel like i would support this project any more. Feel free to create your version which would have pnpm and commitlint, good luck 🤞

Thank you for your great work and great package!
