### ISSUE TITLE
Adding Code of conduct

### ISSUE THREAD

**Issue by SuNiL-Chau** [irevenko/forge-node-app#3]
Would recommend add code of conduct to your repo for better opensource. For more information have a look the docs link here.

https://docs.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project

**Comment by rluvaton** [comment]
As of https://github.com/irevenko/forge-node-app/issues/1#issuecomment-766406033, it looks like this project will no longer be maintained

**Comment by irevenko** [comment]
@rluvaton 😂 ahhaha thanks for replying!

**Comment by rluvaton** [comment]
@irevenko I think you should state in the README that this project is no longer maintained

**Comment by SuNiL-Chau** [comment]
Yes @rluvaton i think it should be mentioned in README

**Comment by rluvaton** [comment]
@SuNiL-Chau If you want to contribute you can contribute to my fork

**Comment by SuNiL-Chau** [comment]
so @rluvaton are you thinking to maintain it further?

**Comment by rluvaton** [comment]
> so @rluvaton are you thinking to maintain it further?

~I'll try~
Edit: You know what, I don't think I'll have the time for that, sorry...
